import { IScannedEndpoint } from './api';

/**
 * Client-side parser to extract API endpoints from local machine code files
 */
export function extractEndpointsFromCode(content: string, filePath: string): IScannedEndpoint[] {
  const endpoints: IScannedEndpoint[] = [];

  // 1. Check if file is OpenAPI / Swagger JSON
  if (filePath.endsWith('.json') && (content.includes('"openapi"') || content.includes('"swagger"'))) {
    try {
      const parsed = JSON.parse(content);
      const pathsObj = parsed.paths || {};
      for (const [apiPath, pathItem] of Object.entries(pathsObj)) {
        if (!pathItem || typeof pathItem !== 'object') continue;
        for (const [methodKey, operation] of Object.entries(pathItem as Record<string, any>)) {
          const method = methodKey.toUpperCase();
          if (['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD'].includes(method)) {
            endpoints.push({
              method: method as any,
              path: apiPath,
              sourceFile: filePath,
              line: 1,
              framework: 'OpenAPI Spec',
              suggestedBody: method !== 'GET' ? '{\n  "example": "data"\n}' : '',
              expectedStatus: method === 'POST' ? 201 : 200,
            });
          }
        }
      }
      if (endpoints.length > 0) return endpoints;
    } catch {
      // fallback to regex if JSON parse fails
    }
  }

  // 2. Next.js App Router API Route detection (app/api/.../route.ts)
  if (filePath.includes('/api/') && (filePath.endsWith('route.ts') || filePath.endsWith('route.js'))) {
    const routePathMatch = filePath.match(/(?:app|pages)\/api\/(.+)\/route\.[jt]s$/);
    const apiPath = routePathMatch ? `/api/${routePathMatch[1]}` : '/api/route';
    const methodRegex = /export\s+async\s+function\s+(GET|POST|PUT|PATCH|DELETE|HEAD)/g;
    let match;
    while ((match = methodRegex.exec(content)) !== null) {
      endpoints.push({
        method: match[1] as any,
        path: apiPath,
        sourceFile: filePath,
        line: content.substring(0, match.index).split('\n').length,
        framework: 'Next.js API Route',
        suggestedBody: match[1] === 'POST' || match[1] === 'PUT' ? '{\n  "key": "value"\n}' : '',
        expectedStatus: 200,
      });
    }
  }

  // 3. Express / Node.js / Fastify / NestJS regex: app.get('/route', ...), router.post('/route', ...)
  const expressRegex = /(?:app|router|server)\.(get|post|put|patch|delete|head)\s*\(\s*['"`]([^'"`]+)['"`]/gi;
  let matchExp;
  while ((matchExp = expressRegex.exec(content)) !== null) {
    const method = matchExp[1].toUpperCase() as any;
    const path = matchExp[2];
    const lineNum = content.substring(0, matchExp.index).split('\n').length;

    let bodyStr = '';
    if (method === 'POST' || method === 'PUT') {
      if (path.toLowerCase().includes('login') || path.toLowerCase().includes('auth')) {
        bodyStr = JSON.stringify({ email: 'user@example.com', password: 'password123' }, null, 2);
      } else {
        bodyStr = JSON.stringify({ name: 'Sample Payload', active: true }, null, 2);
      }
    }

    endpoints.push({
      method,
      path,
      sourceFile: filePath,
      line: lineNum,
      framework: 'Express.js / Node',
      suggestedBody: bodyStr,
      expectedStatus: method === 'POST' ? 201 : 200,
    });
  }

  // 4. Python Flask / FastAPI regex: @app.get('/route'), @router.post('/route')
  const pythonRegex = /@(?:app|router)\.(get|post|put|patch|delete)\s*\(\s*['"`]([^'"`]+)['"`]/gi;
  let matchPy;
  while ((matchPy = pythonRegex.exec(content)) !== null) {
    const method = matchPy[1].toUpperCase() as any;
    const path = matchPy[2];
    const lineNum = content.substring(0, matchPy.index).split('\n').length;
    endpoints.push({
      method,
      path,
      sourceFile: filePath,
      line: lineNum,
      framework: 'FastAPI / Flask',
      suggestedBody: method === 'POST' ? '{\n  "sample": "data"\n}' : '',
      expectedStatus: 200,
    });
  }

  // 5. Go Gin / Echo regex: r.GET("/path", ...), r.POST("/path", ...)
  const goRegex = /\.(GET|POST|PUT|PATCH|DELETE)\s*\(\s*['"`]([^'"`]+)['"`]/g;
  let matchGo;
  while ((matchGo = goRegex.exec(content)) !== null) {
    const method = matchGo[1].toUpperCase() as any;
    const path = matchGo[2];
    const lineNum = content.substring(0, matchGo.index).split('\n').length;
    endpoints.push({
      method,
      path,
      sourceFile: filePath,
      line: lineNum,
      framework: 'Go Gin / Echo',
      suggestedBody: method === 'POST' ? '{\n  "payload": "go_sample"\n}' : '',
      expectedStatus: 200,
    });
  }

  return endpoints;
}

export interface IParsedAiSpecResult {
  steps: any[];
  suggestions: string[];
  workflowName?: string;
  description?: string;
}

/**
 * Parses a markdown specification file generated by local AI agents (Cursor, Antigravity, Copilot, Claude)
 * into Flow Runner workflow steps and system upgrade suggestions.
 */
export function parseWakeUpMarkdownSpec(mdContent: string): IParsedAiSpecResult {
  const steps: any[] = [];
  const suggestions: string[] = [];
  let workflowName = '';
  let description = '';

  // Extract Title / Name
  const titleMatch = mdContent.match(/^#\s+(.+)$/m);
  if (titleMatch) {
    workflowName = titleMatch[1].trim();
  }

  // Extract Suggestions / Recommendations section
  const suggestionsMatch = mdContent.match(/(?:##|#)\s*(?:AI\s+)?(?:Suggestions|Recommendations|System\s+Upgrade[s]?|Enhancement[s]?)([\s\S]*?)(?=\n#|\n##|$)/i);
  if (suggestionsMatch) {
    const rawSuggestions = suggestionsMatch[1];
    const bulletMatches = rawSuggestions.match(/^\s*[-*•\d+.]\s+(.+)$/gm);
    if (bulletMatches) {
      bulletMatches.forEach((line) => {
        const clean = line.replace(/^\s*[-*•\d+.]\s+/, '').trim();
        if (clean) suggestions.push(clean);
      });
    }
  }

  // Split by Step headers (## Step N: ...)
  const stepBlocks = mdContent.split(/(?=^##\s+Step\s+\d+:|^##\s+Step\s+|^###\s+Step\s+\d+:)/m);

  stepBlocks.forEach((block, idx) => {
    const isStepBlock =
      block.toLowerCase().includes('- **method**') ||
      block.toLowerCase().includes('- **url**') ||
      block.toLowerCase().includes('method:') ||
      block.toLowerCase().includes('url:');

    if (!isStepBlock) return;

    const nameMatch = block.match(/^(?:##|###)\s*(Step\s*\d*[:\-]?\s*[^\n]+)/m);
    const stepName = nameMatch ? nameMatch[1].trim() : `Step ${steps.length + 1}: API Endpoint`;

    const methodMatch = block.match(/-\s*\*\*Method\*\*:\s*`?([A-Z]+)`?/i) || block.match(/Method:\s*`?([A-Z]+)`?/i);
    const method = (methodMatch ? methodMatch[1].toUpperCase() : 'GET') as any;

    const urlMatch = block.match(/-\s*\*\*URL\*\*:\s*`?([^\n`]+)`?/i) || block.match(/URL:\s*`?([^\n`]+)`?/i);
    const url = urlMatch ? urlMatch[1].trim() : 'http://localhost:5000/api';

    // Parse Headers
    const headers: Record<string, string> = {};
    const headersBlockMatch = block.match(/-\s*\*\*Headers\*\*:([\s\S]*?)(?=-\s*\*\*|\n#|$)/i);
    if (headersBlockMatch) {
      const headerLines = headersBlockMatch[1].match(/-\s*`?([\w-]+)`?:\s*`?([^\n`]+)`?/g);
      if (headerLines) {
        headerLines.forEach((hl) => {
          const m = hl.match(/-\s*`?([\w-]+)`?:\s*`?([^\n`]+)`?/);
          if (m) {
            headers[m[1].trim()] = m[2].trim();
          }
        });
      }
    }

    // Parse Body Payload
    let bodyPayload = '';
    const jsonCodeBlockMatch = block.match(/```(?:json)?\s*\n([\s\S]*?)\n```/i);
    if (jsonCodeBlockMatch) {
      bodyPayload = jsonCodeBlockMatch[1].trim();
    }

    // Parse Variable Extractions
    const extractVariables: any[] = [];
    const extractBlockMatch = block.match(/-\s*\*\*Extract Variables\*\*:([\s\S]*?)(?=-\s*\*\*|\n#|$)/i);
    if (extractBlockMatch) {
      const extLines = extractBlockMatch[1].match(/-\s*`?([\w.-]+)`?\s+from\s+`?([^\n`]+)`?/gi);
      if (extLines) {
        extLines.forEach((el) => {
          const m = el.match(/-\s*`?([\w.-]+)`?\s+from\s+`?([^\n`]+)`?/i);
          if (m) {
            extractVariables.push({
              varName: m[1].trim(),
              jsonPath: m[2].trim(),
            });
          }
        });
      }
    }

    const carryCookies = block.toLowerCase().includes('carry cookies: true') || block.toLowerCase().includes('carrycookies: true');

    steps.push({
      stepId: `step-${Date.now()}-${idx}`,
      name: stepName,
      method,
      url,
      headers,
      queryParams: {},
      bodyPayload,
      expectedStatusCode: method === 'POST' ? 201 : 200,
      captureCookies: true,
      carryCookies: carryCookies || idx > 0,
      skipped: false,
      extractVariables,
    });
  });

  return {
    workflowName: workflowName || 'AI Generated API Workflow',
    description: description || 'Multi-step API testing chain parsed from local AI agent specification',
    steps,
    suggestions,
  };
}
